package uwc

//partial language codes
const (
	Afrikaans          = "af"
	Albanian           = "sq"
	Amharic            = "am"
	Arabic             = "ar"
	Armenian           = "hy"
	Assamese           = "as"
	Azerbaijani        = "az"
	Bangla             = "bn"
	Bashkir            = "ba"
	Basque             = "eu"
	Bosnian            = "bs"
	Bulgarian          = "bg"
	Cantonese          = "yue"
	Catalan            = "ch"
	Chinese            = "lzh"
	ChineseSimplified  = "zh-Hans"
	ChineseTraditional = "zh-Hant"
	Croatian           = "hr"
	Czech              = "cs"
	Danish             = "da"
	Dari               = "drs"
	Divehi             = "dv"
	Dutch              = "nl"
	English            = "en"
	Estonian           = "et"
	Faroese            = "fo"
	Fijian             = "fj"
	Filipino           = "fil"
	Finnish            = "fi"
	French             = "fr"
	CanadaFr           = "ca-fr"
	Galician           = "gl"
	Georgian           = "gl"
	German             = "de"
)
